[package]
name = "langl"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
chrono = "0.4.38"
either = "1.13.0"
# egui = "0.29.1"
# egui-modal = "0.5.0"
iced = {version = "0.13.1", features=["advanced"]}
rand = "0.8.5"
rfd = { version = "0.15.1" }
walkdir = "2.5.0"
